spring:
  application:
    name: EMR

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emr_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: java1234

  thymeleaf:
    cache: false

  # JPA 설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # 자동 생성된 SQL을 로그에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 이쁘게

server:
  port: 8091

flask:
  url: http://127.0.0.1:5050/

